suppost to fail

diff --git a/.github/workflows/goldenimage-workflow.yml b/.github/workflows/goldenimage-workflow.yml
--- a/.github/workflows/goldenimage-workflow.yml
+++ b/.github/workflows/goldenimage-workflow.yml
@@ -11,10 +11,10 @@ jobs:
     runs-on: ubuntu-latest
     continue-on-error: false  
     steps:
-      - name: Intentional Fail Step
+      - name: Fail Task
         run: |
           echo "This task is designed to fail"
-          exit 1  # This command causes the step to fail with a non-zero exit code.
+          exit 1  # This will cause the step to fail
 
       - name: Notify Discord for success
         if: success()
