no message

diff --git a/.github/workflows/goldenimage-workflow.yml b/.github/workflows/goldenimage-workflow.yml
--- a/.github/workflows/goldenimage-workflow.yml
+++ b/.github/workflows/goldenimage-workflow.yml
@@ -11,6 +11,11 @@ jobs:
     runs-on: ubuntu-latest
     continue-on-error: false  
     steps:
+      - name: Intentional Fail Step
+        run: |
+          echo "This task is designed to fail"
+          exit 1  # This command causes the step to fail with a non-zero exit code.
+
       - name: Notify Discord for success
         if: success()
         uses: discord-actions/message@v2
@@ -24,8 +29,3 @@ jobs:
         with:
           webhookUrl: https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE
           message: "Hello, thats a fail"
-
-      - name: Intentional Fail Step
-        run: |
-          echo "This task is designed to fail"
-          exit 1  # This command causes the step to fail with a non-zero exit code.
